spring:
  application:
    name: ticket
  
  datasource:
    url: jdbc:mysql://localhost:3306/concert?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: concert
    password: ticket
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  
  profiles:
    active: local

server:
  port: 8080

logging:
  level:
    com.ticket: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace